name: Build Linux
on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Build_and_run_tests:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/0ltsu0/linux_x64_build_docker:latest
          options: --user runner
          #credentials:
          #  username: ${{ github.actor }}
          #  password: ${{ secrets.GHCR_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: chmod
              run: chmod +x -R scripts
            
            - name: Build 
              run: scripts/build_linux.sh
              
            - name: Run tests
              run: scripts/run_test_linux.sh
            
            - name: Store artifacts
              uses: actions/upload-artifact@v4
              with:
                name: "Build_Linux_x64"
                path: build/**
                retention-days: 5

    #Test: TBD
