name: Build Linux
on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: chmod
              run: chmod +x scripts/build_linux.sh
            
            - name: Build project 
              run: scripts/build_linux.sh
            
            - name: Store artifacts
              uses: actions/upload-artifact@v4
              with:
                name: "Build_Linux_x64"
                path: build/**
                retention-days: 5

    #Test: TBD
